/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Certificate;
import BackEnd.CertificateManager;
import BackEnd.CourseManager;
import BackEnd.QuizManager;
import BackEnd.Student;
import BackEnd.UserManager;
import com.formdev.flatlaf.FlatDarkLaf;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ayman
 */
public class CertificatesFrame extends javax.swing.JFrame {

    /**
     * Creates new form CertificatesFrame
     */
    CertificateManager certificateManager;

    public CertificatesFrame(CertificateManager certificateManager) {
        initComponents();
        this.setSize(400, 500);
        this.setLocationRelativeTo(null);
        this.certificateManager = certificateManager;
        fillTable();

    }

    void fillTable() {
        DefaultTableModel model = new DefaultTableModel(new Object[]{"Certificates"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // disables editing
            }
        };
        ArrayList<Certificate> certificates = certificateManager.getAllCertificates();
        for (Certificate certificate : certificates) {
            model.addRow(new Object[]{certificate.getCertificateId()});
        }
        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        showCertificateDetailsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Certificates"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        showCertificateDetailsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showCertificateDetailsButton.setText("Show Certificate Details");
        showCertificateDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCertificateDetailsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(showCertificateDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showCertificateDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showCertificateDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCertificateDetailsButtonActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        UserManager userManager = new UserManager("users.json");
        CourseManager courseManager = new CourseManager("courses.json", userManager);
        if (selectedRow != -1) {
            Certificate certificate = certificateManager.getCertificate(jTable1.getValueAt(selectedRow, 0).toString());
            CertificateDetails certificateDetails = new CertificateDetails(certificate, userManager.getUserFromID(certificate.getStudentId()).getUsername(), courseManager.getCourseFromID(certificate.getCourseId()).getTitle());
            certificateDetails.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No certificate selected! please try again.", "Selection warining", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_showCertificateDetailsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // Set FlatLaf Dark look and feel
            FlatDarkLaf.setup();

        } catch (Exception ex) {
            System.err.println("Failed to initialize FlatLaf");
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CertificatesFrame(new CertificateManager(new CourseManager("", new UserManager("")), new UserManager(""))).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton showCertificateDetailsButton;
    // End of variables declaration//GEN-END:variables
}
