/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Certificate;
import com.formdev.flatlaf.FlatDarkLaf;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ayman
 */
public class CertificateDetails extends javax.swing.JFrame {

    /**
     * Creates new form CertificateDetails
     */
    Certificate certificate;
    String studentName;
    String coursetitle;

    public CertificateDetails(Certificate certificate, String studentName, String coursetitle) {
        initComponents();
        this.setSize(500, 500);
        this.setLocationRelativeTo(null);
        this.certificate = certificate;
        this.studentName = studentName;
        this.coursetitle = coursetitle;

        certificateIdLabel.setText(certificate.getCertificateId());
        stdNameLabel.setText(studentName + "(" + certificate.getStudentId() + ")");
        courseNameLabel.setText(coursetitle + "(" + certificate.getCourseId()+ ")");
        fillTable();
    }
    private void fillTable(){
        DefaultTableModel model = new DefaultTableModel(new Object[]{"Quiz ID", "Score"}, 0);
        Map<String, Double> performance = certificate.getPerformance();
        for (Map.Entry<String, Double> entry : performance.entrySet()) {
            String quizId = entry.getKey();
            double score = entry.getValue();
            model.addRow(new Object[]{quizId, score});
        }
        scoresTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        certificateIdLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scoresTable = new javax.swing.JTable();
        stdNameLabel = new javax.swing.JLabel();
        courseNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        certificateIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        certificateIdLabel.setText("Certificate ID");

        scoresTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        scoresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quiz ID", "Score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scoresTable.getTableHeader().setResizingAllowed(false);
        scoresTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(scoresTable);

        stdNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stdNameLabel.setText("Student Name & ID");

        courseNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        courseNameLabel.setText("Course Name & ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(certificateIdLabel)
                            .addComponent(stdNameLabel)
                            .addComponent(courseNameLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(certificateIdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stdNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(courseNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // Set FlatLaf Dark look and feel
            FlatDarkLaf.setup();

        } catch (Exception ex) {
            System.err.println("Failed to initialize FlatLaf");
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CertificateDetails(new Certificate("","","",new HashMap<String, Double>()), "", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel certificateIdLabel;
    private javax.swing.JLabel courseNameLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable scoresTable;
    private javax.swing.JLabel stdNameLabel;
    // End of variables declaration//GEN-END:variables
}
