/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Course;
import BackEnd.CourseManager;
import BackEnd.Lesson;
import BackEnd.Student;
import BackEnd.User;
import BackEnd.UserManager;
import com.formdev.flatlaf.FlatDarkLaf;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ayman
 */
public class CourseForm extends javax.swing.JFrame {

    /**
     * Creates new form CourseForm
     */
    private DefaultTableModel lessonsModel;
    private DefaultTableModel coursesModel;
    private Course courseToModiy;
    private CourseManager courseManager;
    UserManager userManager;
    String instructorID;

    public CourseForm(DefaultTableModel parentModel, String instructorID) {
        initComponents();
        this.coursesModel = parentModel;
        this.setSize(500, 600);
        this.setLocationRelativeTo(null);
        lessonsModel = new DefaultTableModel(new Object[]{"ID", "Title", "Content"}, 0);
        lessonsTable.setModel(lessonsModel);
        courseManager = new CourseManager("courses.json");
        userManager = new UserManager("users.json");
        instructorIDText.setText(instructorID);
        this.instructorID = instructorID;
        addModifyButton.setText("Add");

    }

    public CourseForm(Course course, DefaultTableModel parentModel,String userID) {
        initComponents();
        this.coursesModel = parentModel;
        courseToModiy = course;
        courseManager = new CourseManager("courses.json");
        this.setSize(500, 600);
        this.setLocationRelativeTo(null);
        fillForm(course);
        addModifyButton.setText("Update");
        instructorIDText.setText(userID);
    }

    private void fillForm(Course course) {
        courseIDtext.setText(course.getCourseID());
        courseTitleText.setText(course.getTitle());
        descriptionText.setText(course.getDescription());
        lessonsModel = new DefaultTableModel(new Object[]{"ID", "Title", "Content"}, 0);
        for (Lesson l : course.getLessons()) {
            lessonsModel.addRow(new Object[]{l.getId(), l.getTitle(), l.getContent()});
        }
        lessonsTable.setModel(lessonsModel);
        for (int i = 1; i <= course.getEnrolledStudents().size(); i++) {
            studentsText.append(i + "- " + course.getEnrolledStudents().get(i - 1) + "\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        courseIDtext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        courseTitleText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        instructorIDText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionText = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        studentsText = new javax.swing.JTextArea();
        addModifyButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        lessonsTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Course ID:");

        courseIDtext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Course Title:");

        courseTitleText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Instructor ID:");

        instructorIDText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        instructorIDText.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        instructorIDText.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Description:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Students:");

        descriptionText.setColumns(20);
        descriptionText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        descriptionText.setLineWrap(true);
        descriptionText.setRows(5);
        descriptionText.setWrapStyleWord(true);
        jScrollPane2.setViewportView(descriptionText);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Lessons:");

        studentsText.setEditable(false);
        studentsText.setColumns(20);
        studentsText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        studentsText.setRows(5);
        studentsText.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        studentsText.setEnabled(false);
        jScrollPane3.setViewportView(studentsText);

        addModifyButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addModifyButton.setText("Add");
        addModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addModifyButtonActionPerformed(evt);
            }
        });

        lessonsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lesson ID", "Title", "Content"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(lessonsTable);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("-");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(courseTitleText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(instructorIDText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(courseIDtext))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(addModifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(courseIDtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(courseTitleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(instructorIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(addModifyButton)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        lessonsModel.addRow(new Object[]{"ID", "Title", "Content"});
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addModifyButtonActionPerformed

        Course course;
        String courseID = courseIDtext.getText();
        String title = courseTitleText.getText();
        
        String description = descriptionText.getText();
        String idPattern = "^[A-Za-z][0-9]+$";

        if (courseID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Course ID cannot be empty!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (title.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Course Title cannot be empty!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (description.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Description cannot be empty!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!courseID.matches(idPattern)) {
            JOptionPane.showMessageDialog(this, "Course ID must start with a letter followed by numbers (e.g., C123).", "Invalid ID", JOptionPane.WARNING_MESSAGE);
            return;
        }
        ArrayList<Lesson> lessons = new ArrayList<>();
        for (int row = 0; row < lessonsTable.getRowCount(); row++) {
            String lessonID = lessonsModel.getValueAt(row, 0).toString().trim();
            String lessonTitle = lessonsModel.getValueAt(row, 1).toString().trim();
            String lessonContent = lessonsModel.getValueAt(row, 2).toString().trim();
            if (lessonID.isEmpty() || lessonTitle.isEmpty() || lessonContent.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Lesson fields cannot be empty!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (!lessonID.matches(idPattern)) {
                JOptionPane.showMessageDialog(this, "Lesson ID must start with a letter then numbers (e.g., L01).", "Invalid Lesson ID", JOptionPane.WARNING_MESSAGE);
                return;
            }
            lessons.add(new Lesson(lessonsModel.getValueAt(row, 0).toString(), lessonsModel.getValueAt(row, 1).toString(), lessonsModel.getValueAt(row, 2).toString()));
        }

        course = new Course(courseID, title, description, instructorID, lessons);
        if (!studentsText.getText().trim().isEmpty()) {
            course.setEnrolledStudents(courseToModiy.getEnrolledStudents());
        }
        if (courseToModiy == null) {
            courseManager.addCourse(course);
            coursesModel.addRow(new Object[]{course.getCourseID(), course.getTitle(), course.getInstructorId()});
            userManager.courseCreated(courseID, instructorID);
            JOptionPane.showMessageDialog(this, "Course added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            courseManager.modifyCourse(courseToModiy.getCourseID(), course);
            JOptionPane.showMessageDialog(this, "Course updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
        for (int i = 0; i < coursesModel.getRowCount(); i++) {
            if (coursesModel.getValueAt(i, 0).equals(course.getCourseID())) {
                coursesModel.setValueAt(course.getTitle(), i, 1);
                coursesModel.setValueAt(course.getInstructorId(), i, 2);
                break;
            }
        }
        dispose();
    }//GEN-LAST:event_addModifyButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = lessonsTable.getSelectedRow();
        if (selectedRow != -1) {
            lessonsModel.removeRow(selectedRow);
        } else {
            JOptionPane.showMessageDialog(this, "No lesson selected! please try again.", "Selection warining", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // Set FlatLaf Dark look and feel
            FlatDarkLaf.setup();

        } catch (Exception ex) {
            System.err.println("Failed to initialize FlatLaf");
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseForm(new DefaultTableModel(),"").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addModifyButton;
    private javax.swing.JTextField courseIDtext;
    private javax.swing.JTextField courseTitleText;
    private javax.swing.JTextArea descriptionText;
    private javax.swing.JTextField instructorIDText;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable lessonsTable;
    private javax.swing.JTextArea studentsText;
    // End of variables declaration//GEN-END:variables
}
