/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Course;
import BackEnd.Lesson;
import BackEnd.User;
import com.formdev.flatlaf.FlatDarkLaf;
import java.util.ArrayList;

/**
 *
 * @author Ayman
 */
public class CourseDetails extends javax.swing.JFrame {

    /**
     * Creates new form CourseDetails
     */
    public CourseDetails(Course course) {
        initComponents();
        this.setSize(500, 600);
        this.setLocationRelativeTo(null);
        fillForm(course);
    }

    private void fillForm(Course course) {
        courseIDLabel.setText(course.getCourseID() + ":");
        courseTitleLabel.setText(course.getTitle());
        instructorIDLabel.setText(course.getInstructorId());
        descriptionTextArea.setText(course.getDescription());
        for (Lesson l : course.getLessons()) {
            lessonsTextArea.append(l.getId() + "-" + l.getTitle() + ": " + l.getContent() + "\n");
        }
//        for (User u : course.getEnrolledStudents()) {
//            enrolledStudentsTextArea1.append(u.getUserId() + "\t");
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        courseTitleLabel = new javax.swing.JLabel();
        courseIDLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enrolledStudentsTextArea1 = new javax.swing.JTextArea();
        instructorIDLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        lessonsTextArea = new javax.swing.JTextArea();
        instructorIDLabel1 = new javax.swing.JLabel();
        instructorIDLabel2 = new javax.swing.JLabel();
        instructorIDLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        courseTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        courseTitleLabel.setText("CourseTitle");

        courseIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        courseIDLabel.setText("C-001:");

        enrolledStudentsTextArea1.setColumns(20);
        enrolledStudentsTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        enrolledStudentsTextArea1.setLineWrap(true);
        enrolledStudentsTextArea1.setRows(5);
        enrolledStudentsTextArea1.setWrapStyleWord(true);
        enrolledStudentsTextArea1.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        enrolledStudentsTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(enrolledStudentsTextArea1);

        instructorIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        instructorIDLabel.setText("I-001");

        descriptionTextArea.setEditable(false);
        descriptionTextArea.setColumns(20);
        descriptionTextArea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        descriptionTextArea.setLineWrap(true);
        descriptionTextArea.setRows(5);
        descriptionTextArea.setWrapStyleWord(true);
        descriptionTextArea.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        descriptionTextArea.setEnabled(false);
        jScrollPane2.setViewportView(descriptionTextArea);

        lessonsTextArea.setColumns(20);
        lessonsTextArea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lessonsTextArea.setLineWrap(true);
        lessonsTextArea.setRows(5);
        lessonsTextArea.setWrapStyleWord(true);
        lessonsTextArea.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        lessonsTextArea.setEnabled(false);
        jScrollPane3.setViewportView(lessonsTextArea);

        instructorIDLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        instructorIDLabel1.setText("Description:");

        instructorIDLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        instructorIDLabel2.setText("Lessons:");

        instructorIDLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        instructorIDLabel3.setText("Enrolled Student:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(instructorIDLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(instructorIDLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(instructorIDLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(courseIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(courseTitleLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(instructorIDLabel)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseIDLabel)
                    .addComponent(courseTitleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructorIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(instructorIDLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructorIDLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructorIDLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // Set FlatLaf Dark look and feel
            FlatDarkLaf.setup();

        } catch (Exception ex) {
            System.err.println("Failed to initialize FlatLaf");
        }
        ArrayList<Lesson> lessons = new ArrayList<>();
        lessons.add(new Lesson("L1", "Introduction", "content"));
        lessons.add(new Lesson("L2", "Basic Concepts", "content"));
        lessons.add(new Lesson("L3", "Advanced Topics", "content"));
        lessons.add(new Lesson("L3", "Advanced Topics", "content"));
        lessons.add(new Lesson("L3", "Advanced Topics", "content"));
        lessons.add(new Lesson("L3", "Advanced Topics", "content"));
        lessons.add(new Lesson("L3", "Advanced Topics", "content"));
        lessons.add(new Lesson("L3", "Advanced Topics", "content"));

// Create the test course
        Course testCourse = new Course(
                "C101", // courseID
                "Java Programming", // title
                "The goal of this phase is to implement all functionalities for Students and \n"
                + "Instructors, focusing on course creation, learning progress, and lesson \n"
                + "interaction. \n"
                + "The system should support teaching and learning workflows before adding \n"
                + "administrative oversight. ",
                "INST123",
                lessons
        );

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseDetails(testCourse).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel courseIDLabel;
    private javax.swing.JLabel courseTitleLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JTextArea enrolledStudentsTextArea1;
    private javax.swing.JLabel instructorIDLabel;
    private javax.swing.JLabel instructorIDLabel1;
    private javax.swing.JLabel instructorIDLabel2;
    private javax.swing.JLabel instructorIDLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea lessonsTextArea;
    // End of variables declaration//GEN-END:variables
}
