/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Lesson;
import BackEnd.Question;
import BackEnd.Quiz;
import com.formdev.flatlaf.FlatDarkLaf;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ayman
 */
public class LessonForm extends javax.swing.JFrame {

    /**
     * Creates new form LessonForm
     */
    Quiz quiz;
    DefaultTableModel quizModel;
    private LessonCallback callback;

    public LessonForm(LessonCallback callback) {
        initComponents();

        this.callback = callback;
        this.setSize(800, 600);
        this.setLocationRelativeTo(null);
        quizModel = new DefaultTableModel(new Object[]{"Question", "Option A", "Option B", "Option C", "Correct Option"}, 0);
        quizTable.setModel(quizModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        quizTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        IDfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        contentTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        addQuestionButton = new javax.swing.JButton();
        saveLessonButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        quizTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        quizTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Question", "Option A", "Option B", "Option C", "Correct Option"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        quizTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(quizTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Lesson ID:");

        IDfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Lesson Title:");

        titleField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Lesson content:");

        contentTextArea.setColumns(20);
        contentTextArea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contentTextArea.setRows(5);
        jScrollPane2.setViewportView(contentTextArea);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Lesson Quiz:");

        addQuestionButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addQuestionButton.setText("Add Question");
        addQuestionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuestionButtonActionPerformed(evt);
            }
        });

        saveLessonButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveLessonButton.setText("Save Lesson");
        saveLessonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveLessonButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addQuestionButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveLessonButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDfield, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(IDfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addQuestionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(228, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveLessonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveLessonButtonActionPerformed
        // TODO add your handling code here:
        String lessonID = IDfield.getText().trim();
        String lessonTitle = titleField.getText().trim();
        String content = contentTextArea.getText().trim();
        ArrayList<Question> questions = new ArrayList<Question>();
        for (int row = 0; row < quizTable.getRowCount(); row++) {
            String question = quizModel.getValueAt(row, 0).toString().trim();
            String optionA = quizModel.getValueAt(row, 1).toString().trim();
            String optionB = quizModel.getValueAt(row, 2).toString().trim();
            String optionC = quizModel.getValueAt(row, 3).toString().trim();
            String correctOption = quizModel.getValueAt(row, 4).toString().toUpperCase().trim();

            if (question.isEmpty() || optionA.isEmpty() || optionB.isEmpty() || optionC.isEmpty() || correctOption.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Quiz fields cannot be empty!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            char correctOptionchar = correctOption.charAt(0);
            if (correctOption.length() != 1 || !(correctOption.equals("A") || correctOption.equals("B") || correctOption.equals("C"))) {
                JOptionPane.showMessageDialog(this, "Correct option must be A,B or C!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            ArrayList<String> options = new ArrayList<String>();
            options.add(optionA);
            options.add(optionB);
            options.add(optionC);
            questions.add(new Question(question, options, correctOptionchar));
        }
        if (questions.size() == 0) {
                JOptionPane.showMessageDialog(this, "Every lesson must have a quiz!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        quiz = new Quiz("Q"+lessonID,questions);
        Lesson lesson = new Lesson(lessonID, lessonTitle, content);
        lesson.setQuiz(quiz);
        callback.onLessonCreated(lesson);
        JOptionPane.showMessageDialog(this, "Lesson added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }//GEN-LAST:event_saveLessonButtonActionPerformed

    private void addQuestionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuestionButtonActionPerformed
        // TODO add your handling code here:
        quizModel.addRow(new Object[]{"Question", "Option A", "Option B", "Option C", "Correct Option"});
    }//GEN-LAST:event_addQuestionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // Set FlatLaf Dark look and feel
            FlatDarkLaf.setup();

        } catch (Exception ex) {
            System.err.println("Failed to initialize FlatLaf");
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LessonForm(new LessonCallback() {
                    @Override
                    public void onLessonCreated(Lesson lesson) {

                    }
                }).setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDfield;
    private javax.swing.JButton addQuestionButton;
    private javax.swing.JTextArea contentTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable quizTable;
    private javax.swing.JButton saveLessonButton;
    private javax.swing.JTextField titleField;
    // End of variables declaration//GEN-END:variables
}
