/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd;

/**
 *
 * @author Ayman
 */
import BackEnd.Question;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.SwingUtilities;

public class QuestionPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuestionPanel
     */
    private Question question;
    private ButtonGroup group = new ButtonGroup();
    private JRadioButton[] radios = new JRadioButton[3];

    public QuestionPanel(Question question, int number) {
        this.question = question;
        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        //setBorder(BorderFactory.createLineBorder(Color.GRAY));

        JLabel questionLabel = new JLabel(number + ". " + question.getQuestionText());
        questionLabel.setFont(new Font("Arial", Font.BOLD, 18));
        add(questionLabel);

        for (int i = 0; i < question.getChoices().size(); i++) {
            radios[i] = new JRadioButton(question.getChoices().get(i));
            radios[i].setActionCommand(String.valueOf((char) ('A' + i))); // A, B, C
            radios[i].setFont(new Font("Arial", Font.BOLD, 14));
            group.add(radios[i]);
            add(radios[i]);
        }
    }

    // Get selected answer
    public String getSelectedAnswer() {
        if (group.getSelection() == null) {
            return "";
        }
        return group.getSelection().getActionCommand();
    }

    // Get correct answer
    public char getCorrectAnswer() {
        return question.getCorrectChoice();
    }

    public void showResult() {
        String selected = getSelectedAnswer();
        String correct = String.valueOf(question.getCorrectChoice());

        for (JRadioButton radio : radios) {
            String action = radio.getActionCommand();

            if (action.equals(correct)) {

                radio.setForeground(Color.GREEN);
            } else if (action.equals(selected)) {

                radio.setForeground(Color.RED);
            } else {

                radio.setForeground(Color.BLACK);
            }
            radio.setFocusable(false);
        }
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {

            // Create sample question
            ArrayList<String> choices = new ArrayList<>();
            choices.add("Option A");
            choices.add("Option B");
            choices.add("Option C");

            Question sample = new Question(
                    "What does OOP stand for?",
                    choices,
                    'A'
            );

            JFrame frame = new JFrame("Question Panel Test");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setSize(400, 250);
            frame.setLocationRelativeTo(null);

            QuestionPanel panel = new QuestionPanel(sample, 1);
            frame.add(panel);

            frame.setVisible(true);
        });


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
}
