/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.CourseManager;
import BackEnd.Question;
import BackEnd.Quiz;
import BackEnd.QuizManager;
import BackEnd.Student;
import BackEnd.UserManager;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Ayman
 */
public class QuizFrame extends javax.swing.JFrame {

    /**
     * Creates new form QuizFrame
     */
    private Quiz quiz;
    QuizManager quizManager;
    Student student;
    CourseManager courseManager;
    String courseID;
    private ArrayList<QuestionPanel> questionPanels = new ArrayList<>();

    public QuizFrame(Quiz quiz, QuizManager quizManager, Student student, CourseManager courseManager, String courseID) {
        this.quiz = quiz;
        this.quizManager = quizManager;
        this.student = student;
        this.courseManager = courseManager;
        this.courseID = courseID;
        setTitle("Quiz");
        setSize(700, 600);
        setLocationRelativeTo(null);

        JPanel container = new JPanel();
        container.setLayout(new BoxLayout(container, BoxLayout.Y_AXIS));

        JScrollPane scrollPane = new JScrollPane(container);
        add(scrollPane, BorderLayout.CENTER);

        int number = 1;

        for (Question q : quiz.getQuestions()) {
            QuestionPanel qp = new QuestionPanel(q, number++);
            questionPanels.add(qp);
            container.add(qp);
            container.add(Box.createVerticalStrut(10));
        }

        JButton submitBtn = new JButton("Submit Quiz");
        submitBtn.addActionListener(e -> {
            ArrayList<Character> studentChoices = new ArrayList<Character>();
            for (QuestionPanel qp : questionPanels) {
                studentChoices.add(qp.getSelectedAnswer().charAt(0));
            }
            double score = quizManager.isPassed(student, quiz.getQuizID(), studentChoices);
            courseManager.setQuizScore(courseID, student.getUserId(), quiz.getQuizID().substring(quiz.getQuizID().indexOf("L")), score);
            JOptionPane.showMessageDialog(this, "Score: " + score + " % ");
        });

        JPanel bottomPanel = new JPanel();
        bottomPanel.add(submitBtn);

        add(bottomPanel, BorderLayout.SOUTH);
    }

    private void calculateScore() {
        int score = 0;

        for (QuestionPanel qp : questionPanels) {
            if (qp.getSelectedAnswer().charAt(0) == qp.getCorrectAnswer()) {
                score++;
            }
            qp.showResult();
        }

        JOptionPane.showMessageDialog(this,
                "Score: " + score + " / " + questionPanels.size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        try {
            // Set FlatLaf Dark look and feel
            FlatDarkLaf.setup();

        } catch (Exception ex) {
            System.err.println("Failed to initialize FlatLaf");
        }
        SwingUtilities.invokeLater(() -> {

            // Create sample questions for testing
            ArrayList<Question> questions = new ArrayList<>();

            // Question 1
            ArrayList<String> options1 = new ArrayList<>();
            options1.add("3");
            options1.add("4");
            options1.add("5");
            questions.add(new Question("What is 2 + 2?", options1, 'B'));

            // Question 2
            ArrayList<String> options2 = new ArrayList<>();
            options2.add("Programming Language");
            options2.add("Operating System");
            options2.add("Browser");
            questions.add(new Question("Java is?", options2, 'A'));

            // Question 3
            ArrayList<String> options3 = new ArrayList<>();
            options3.add("Encapsulation");
            options3.add("Polymorphism");
            options3.add("Compilation");
            questions.add(new Question("Which is not OOP concept?", options3, 'C'));

            // Create quiz and pass questions
            Quiz quiz = new Quiz("Sample Quiz", questions);

            // Show the frame
            QuizFrame frame = new QuizFrame(quiz, new QuizManager(new CourseManager("", new UserManager("")), new UserManager("")), new Student("", "", "", ""), new CourseManager("", new UserManager("")), "");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
